openapi: 3.0.0
info:
  title: Suporte ao Cliente
  version: 0.1.0
  description: Suporte ao Cliente

tags:
  - name: Detalhes do pedido
    description: Detalhes do pedido
  - name: Detalhes do e-mail
    description: Operações relacionadas à recuperação de correspondência

servers:
  - url: https://order-to-cash.21pfvqjn6rrj.us-south.codeengine.appdomain.cloud

paths:
  /get_order_updates/{order_id}:
    get:
      summary: Obtenha detalhes do pedido
      description: Obtenha detalhes do pedido
      operationId: get_order_details_po_get
      tags:
        - Detalhes do pedido
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
            title: Order ID
      responses:
        "200":
          description: Resposta bem sucedida
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderDetails"

  /get_all_orders:
    get:
      summary: Obter todos os pedidos
      description: Obter todos os IDs de pedidos
      operationId: get_all_orders
      tags:
        - Detalhes do pedido
      responses:
        "200":
          description: Resposta bem sucedida
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderIds"

  /get_all_mails:
    get:
      summary: Obter todos os e-mails
      description: Busca todos os registros de e-mail
      operationId: get_all_mails
      tags:
        - Detalhes do e-mail
      responses:
        "200":
          description: Resposta bem sucedida
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MailRecords"

components:
  schemas:
    OrderIds:
      type: object
      properties:
        Orders:
          type: object
          additionalProperties:
            type: string

    OrderDetails:
      type: object
      properties:
        Order_Update:
          type: array
          items:
            type: object
            properties:
              order_id:
                type: string
              order_date:
                type: string
              order_update:
                type: string

    MailRecords:
      type: object
      properties:
        Mail_Records:
          type: object
          properties:
            name:
              type: object
              additionalProperties:
                type: string
            email:
              type: object
              additionalProperties:
                type: string

    HTTPValidationError:
      type: object
      title: HTTPValidationError
      properties:
        detail:
          type: array
          title: Detail
          items:
            $ref: "#/components/schemas/ValidationError"

    ValidationError:
      type: object
      title: ValidationError
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          title: Location
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
